Integrate e2e testing in workflow

diff --git a/.github/workflows/skaffold-test.yml b/.github/workflows/skaffold-test.yml
--- a/.github/workflows/skaffold-test.yml
+++ b/.github/workflows/skaffold-test.yml
@@ -23,7 +23,7 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
-        python-version: 3.9
+        python-version: 3.12
 
     - name: Install Skaffold
       run: |
@@ -35,16 +35,42 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-        pip install pytest
+        pip install pytest grpcio grpcio-tools
 
     - name: Set PYTHONPATH
       run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
+
+    - name: Build Docker Image
+      run: |
+        docker build -t bannerservice:latest .
+
+    - name: Start gRPC Server Container
+      run: |
+        docker run -d --name banner-service -p 51234:51234 bannerservice:latest
+        echo "Waiting for the server to start..."
+
+    - name: Wait for Server Readiness
+      run: |
+        for i in {1..10}; do
+          if grpcurl -plaintext localhost:51234 describe; then
+            echo "Server is ready!"
+            exit 0
+          fi
+           echo "Waiting for the server..."
+          sleep 5
+        done
+        echo "Server failed to start in time."
+        exit 1
 
     - name: Run Unit Tests
       run: pytest -m unit tests/
 
     - name: Run Component Tests
       run: pytest -m component tests/
+
+    - name: Run End-to-End Tests
+      run: pytest -m e2e tests/
+
 
 ## Temporarily disabled
    ## - name: Run Skaffold Tests
@@ -56,3 +82,6 @@ jobs:
       with:
         name: test-results
         path: tests
+
+    - name: Stop and Clean Up Docker Container
+      run: docker stop banner-service && docker rm banner-service
